In [94]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [95]:
class Perceptron:
    def __init__(self, eta, epochs):
        self.weights = np.random.rand(3) * 1e-4
        self.eta = eta
        self.epochs = epochs

        print(f"Self.Weights: {self.weights}")

    def activationFunction(self, inputs, weights):
        z = np.dot(inputs, weights)
        return np.where(z > 0 , 1, 0)

    def fit(self, x, y):
        self.x = x
        self.y = y

        x_with_bias = np.c_[self.x, -np.ones((len(self.x), 1))]
        print(f"X with Bias: {x_with_bias}")

        for epoch in range(self.epochs):
            print(f"Epoch: {epoch}")

            
            y_hat = self.activationFunction(x_with_bias, self.weights) # prediction
            error = self.y - y_hat # error
            self.weights = self.weights + self.eta * np.dot(x_with_bias.T, error) # weight update

            print(f"Predicted Result: {y_hat}")
            print(f"Error: \n{error}")
            print(f"Updated Weights: {self.weights}")
            print("--------------")

    def predict(self, x):
        x_with_bias = np.c_[self.x, -np.ones((len(self.x), 1))]

        return self.activationFunction(x_with_bias, self.weights)

# AND Gate

In [96]:
data = {
    'x1' : [0, 0, 1, 1],
    'x2' : [0, 1, 0, 1],
    'y' : [0, 0, 0, 1]
}

AND = pd.DataFrame(data) 

x = AND.drop('y', axis=1)
y = AND['y']
y.to_frame()

   y
0  0
1  0
2  0
3  1

***Model Prediction***

In [97]:
model = Perceptron(eta=0.5, epochs=10)
model.fit(x,y)

Self.Weights: [1.56018640e-05 1.55994520e-05 5.80836122e-06]
X with Bias: [[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
Epoch: 0
Predicted Result: [0 1 1 1]
Error:
0    0
1   -1
2   -1
3    0
Name: y, dtype: int64
Updated Weights: [-0.4999844  -0.4999844   1.00000581]
--------------
Epoch: 1
Predicted Result: [0 0 0 0]
Error:
0    0
1    0
2    0
3    1
Name: y, dtype: int64
Updated Weights: [1.56018640e-05 1.55994520e-05 5.00005808e-01]
--------------
Epoch: 2
Predicted Result: [0 0 0 0]
Error:
0    0
1    0
2    0
3    1
Name: y, dtype: int64
Updated Weights: [5.00015602e-01 5.00015599e-01 5.80836122e-06]
--------------
Epoch: 3
Predicted Result: [0 1 1 1]
Error:
0    0
1   -1
2   -1
3    0
Name: y, dtype: int64
Updated Weights: [1.56018640e-05 1.55994520e-05 1.00000581e+00]
--------------
Epoch: 4
Predicted Result: [0 0 0 0]
Error:
0    0
1    0
2    0
3    1
Name: y, dtype: int64
Updated Weights: [0.5000156  0.5000156  0.50000581]
--------------
Epoch: 5
Predicted Result: [0 1 1 1]
Error:
0    0
1   -1
2   -1
3    0
Name: y, dtype: int64
Updated Weights: [1.56018640e-05 1.55994520e-05 1.50000581e+00]
--------------
Epoch: 6
Predicted Result: [0 0 0 0]
Error:
0    0
1    0
2    0
3    1
Name: y, dtype: int64
Updated Weights: [0.5000156  0.5000156  1.00000581]
--------------
Epoch: 7
Predicted Result: [0 0 0 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [0.5000156  0.5000156  1.00000581]
--------------
Epoch: 8
Predicted Result: [0 0 0 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [0.5000156  0.5000156  1.00000581]
--------------
Epoch: 9
Predicted Result: [0 0 0 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [0.5000156  0.5000156  1.00000581]
--------------

# OR Gate

In [98]:
data = {
    'x1' : [0, 0, 1, 1],
    'x2' : [0, 1, 0, 1],
    'y' : [0, 1, 1, 1]
}

OR = pd.DataFrame(data) 

x = OR.drop('y', axis=1)
y = OR['y']
y.to_frame()

   y
0  0
1  1
2  1
3  1

***Model Prediction***

In [99]:
model = Perceptron(eta=0.5, epochs=10)
model.fit(x,y)

Self.Weights: [8.66176146e-05 6.01115012e-05 7.08072578e-05]
X with Bias: [[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
Epoch: 0
Predicted Result: [0 0 1 1]
Error:
0    0
1    1
2    0
3    0
Name: y, dtype: int64
Updated Weights: [ 8.66176146e-05  5.00060112e-01 -4.99929193e-01]
--------------
Epoch: 1
Predicted Result: [1 1 1 1]
Error:
0   -1
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 7.08072578e-05]
--------------
Epoch: 2
Predicted Result: [0 1 1 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 7.08072578e-05]
--------------
Epoch: 3
Predicted Result: [0 1 1 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 7.08072578e-05]
--------------
Epoch: 4
Predicted Result: [0 1 1 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 7.08072578e-05]
--------------
Epoch: 5
Predicted Result: [0 1 1 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 7.08072578e-05]
--------------
Epoch: 6
Predicted Result: [0 1 1 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 7.08072578e-05]
--------------
Epoch: 7
Predicted Result: [0 1 1 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 7.08072578e-05]
--------------
Epoch: 8
Predicted Result: [0 1 1 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 7.08072578e-05]
--------------
Epoch: 9
Predicted Result: [0 1 1 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 7.08072578e-05]
--------------

# XOR Gate

**XOR gate couldn't solve**

In [110]:
data = {
    'x1' : [0, 0, 1, 1],
    'x2' : [0, 1, 0, 1],
    'y' : [0, 1, 1, 0]
}

XOR = pd.DataFrame(data) 

x = XOR.drop('y', axis=1)
y = XOR['y']
y.to_frame()

   y
0  0
1  1
2  1
3  0

***Model Prediction***

In [109]:
model = Perceptron(eta=0.5, epochs=10000)
model.fit(x,y)

Self.Weights: [8.66176146e-05 6.01115012e-05 7.08072578e-05]
X with Bias: [[ 0.  0. -1.]
 [ 0.  1. -1.]
 [ 1.  0. -1.]
 [ 1.  1. -1.]]
Epoch: 0
Predicted Result: [0 0 1 1]
Error:
0    0
1    0
2   -1
3    0
Name: y, dtype: int64
Updated Weights: [-4.99913382e-01  6.01115012e-05  5.00070807e-01]
--------------
Epoch: 1
Predicted Result: [0 0 0 0]
Error:
0    0
1    0
2    0
3    1
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 7.08072578e-05]
--------------
Epoch: 2
Predicted Result: [0 1 1 1]
Error:
0    0
1   -1
2   -1
3    0
Name: y, dtype: int64
Updated Weights: [-4.99913382e-01  6.01115012e-05  1.00007081e+00]
--------------
Epoch: 3
Predicted Result: [0 0 0 0]
Error:
0    0
1    0
2    0
3    1
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 5.00070807e-01]
--------------
Epoch: 4
Predicted Result: [0 0 0 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 5.00070807e-01]
--------------
Epoch: 5
Predicted Result: [0 0 0 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 5.00070807e-01]
--------------
Epoch: 6
Predicted Result: [0 0 0 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 5.00070807e-01]
--------------
Epoch: 7
Predicted Result: [0 0 0 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 5.00070807e-01]
--------------
Epoch: 8
Predicted Result: [0 0 0 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 5.00070807e-01]
--------------
Epoch: 9
Predicted Result: [0 0 0 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 5.00070807e-01]
--------------
Epoch: 10
Predicted Result: [0 0 0 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 5.00070807e-01]
--------------
Epoch: 11
Predicted Result: [0 0 0 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 5.00070807e-01]
--------------
Epoch: 12
Predicted Result: [0 0 0 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 5.00070807e-01]
--------------
Epoch: 13
Predicted Result: [0 0 0 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 5.00070807e-01]
--------------
Epoch: 14
Predicted Result: [0 0 0 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 5.00070807e-01]
--------------
Epoch: 15
Predicted Result: [0 0 0 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 5.00070807e-01]
--------------
Epoch: 16
Predicted Result: [0 0 0 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 5.00070807e-01]
--------------
Epoch: 17
Predicted Result: [0 0 0 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 5.00070807e-01]
--------------
Epoch: 18
Predicted Result: [0 0 0 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 5.00070807e-01]
--------------
Epoch: 19
Predicted Result: [0 0 0 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 5.00070807e-01]
--------------
Epoch: 20
Predicted Result: [0 0 0 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 5.00070807e-01]
--------------
Epoch: 21
Predicted Result: [0 0 0 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 5.00070807e-01]
--------------
Epoch: 22
Predicted Result: [0 0 0 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 5.00070807e-01]
--------------
Epoch: 23
Predicted Result: [0 0 0 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 5.00070807e-01]
--------------
Epoch: 24
Predicted Result: [0 0 0 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 5.00070807e-01]
--------------
Epoch: 25
Predicted Result: [0 0 0 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 5.00070807e-01]
--------------
Epoch: 26
Predicted Result: [0 0 0 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 5.00070807e-01]
--------------
Epoch: 27
Predicted Result: [0 0 0 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 5.00070807e-01]
--------------
Epoch: 28
Predicted Result: [0 0 0 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 5.00070807e-01]
--------------
Epoch: 29
Predicted Result: [0 0 0 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 5.00070807e-01]
--------------
Epoch: 30
Predicted Result: [0 0 0 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 5.00070807e-01]
--------------
Epoch: 31
Predicted Result: [0 0 0 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 5.00070807e-01]
--------------
Epoch: 32
Predicted Result: [0 0 0 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 5.00070807e-01]
--------------
Epoch: 33
Predicted Result: [0 0 0 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 5.00070807e-01]
--------------
Epoch: 34
Predicted Result: [0 0 0 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 5.00070807e-01]
--------------
Epoch: 35
Predicted Result: [0 0 0 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 5.00070807e-01]
--------------
Epoch: 36
Predicted Result: [0 0 0 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 5.00070807e-01]
--------------
Epoch: 37
Predicted Result: [0 0 0 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 5.00070807e-01]
--------------
Epoch: 38
Predicted Result: [0 0 0 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 5.00070807e-01]
--------------
Epoch: 39
Predicted Result: [0 0 0 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 5.00070807e-01]
--------------
Epoch: 40
Predicted Result: [0 0 0 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 5.00070807e-01]
--------------
Epoch: 41
Predicted Result: [0 0 0 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 5.00070807e-01]
--------------
Epoch: 42
Predicted Result: [0 0 0 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 5.00070807e-01]
--------------
Epoch: 43
Predicted Result: [0 0 0 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 5.00070807e-01]
--------------
Epoch: 44
Predicted Result: [0 0 0 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 5.00070807e-01]
--------------
Epoch: 45
Predicted Result: [0 0 0 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 5.00070807e-01]
--------------
Epoch: 46
Predicted Result: [0 0 0 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 5.00070807e-01]
--------------
Epoch: 47
Predicted Result: [0 0 0 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 5.00070807e-01]
--------------
Epoch: 48
Predicted Result: [0 0 0 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 5.00070807e-01]
--------------
Epoch: 49
Predicted Result: [0 0 0 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 5.00070807e-01]
--------------
Epoch: 50
Predicted Result: [0 0 0 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 5.00070807e-01]
--------------
Epoch: 51
Predicted Result: [0 0 0 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 5.00070807e-01]
--------------
Epoch: 52
Predicted Result: [0 0 0 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 5.00070807e-01]
--------------
Epoch: 53
Predicted Result: [0 0 0 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 5.00070807e-01]
--------------
Epoch: 54
Predicted Result: [0 0 0 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 5.00070807e-01]
--------------
Epoch: 55
Predicted Result: [0 0 0 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 5.00070807e-01]
--------------
Epoch: 56
Predicted Result: [0 0 0 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 5.00070807e-01]
--------------
Epoch: 57
Predicted Result: [0 0 0 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 5.00070807e-01]
--------------
Epoch: 58
Predicted Result: [0 0 0 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 5.00070807e-01]
--------------
Epoch: 59
Predicted Result: [0 0 0 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 5.00070807e-01]
--------------
Epoch: 60
Predicted Result: [0 0 0 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 5.00070807e-01]
--------------
Epoch: 61
Predicted Result: [0 0 0 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 5.00070807e-01]
--------------
Epoch: 62
Predicted Result: [0 0 0 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 5.00070807e-01]
--------------
Epoch: 63
Predicted Result: [0 0 0 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 5.00070807e-01]
--------------
Epoch: 64
Predicted Result: [0 0 0 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 5.00070807e-01]
--------------
Epoch: 65
Predicted Result: [0 0 0 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 5.00070807e-01]
--------------
Epoch: 66
Predicted Result: [0 0 0 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 5.00070807e-01]
--------------
Epoch: 67
Predicted Result: [0 0 0 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 5.00070807e-01]
--------------
Epoch: 68
Predicted Result: [0 0 0 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 5.00070807e-01]
--------------
Epoch: 69
Predicted Result: [0 0 0 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 5.00070807e-01]
--------------
Epoch: 70
Predicted Result: [0 0 0 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 5.00070807e-01]
--------------
Epoch: 71
Predicted Result: [0 0 0 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 5.00070807e-01]
--------------
Epoch: 72
Predicted Result: [0 0 0 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 5.00070807e-01]
--------------
Epoch: 73
Predicted Result: [0 0 0 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 5.00070807e-01]
--------------
Epoch: 74
Predicted Result: [0 0 0 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 5.00070807e-01]
--------------
Epoch: 75
Predicted Result: [0 0 0 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 5.00070807e-01]
--------------
Epoch: 76
Predicted Result: [0 0 0 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 5.00070807e-01]
--------------
Epoch: 77
Predicted Result: [0 0 0 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 5.00070807e-01]
--------------
Epoch: 78
Predicted Result: [0 0 0 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 5.00070807e-01]
--------------
Epoch: 79
Predicted Result: [0 0 0 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 5.00070807e-01]
--------------
Epoch: 80
Predicted Result: [0 0 0 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 5.00070807e-01]
--------------
Epoch: 81
Predicted Result: [0 0 0 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 5.00070807e-01]
--------------
Epoch: 82
Predicted Result: [0 0 0 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 5.00070807e-01]
--------------
Epoch: 83
Predicted Result: [0 0 0 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 5.00070807e-01]
--------------
Epoch: 84
Predicted Result: [0 0 0 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 5.00070807e-01]
--------------
Epoch: 85
Predicted Result: [0 0 0 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 5.00070807e-01]
--------------
Epoch: 86
Predicted Result: [0 0 0 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 5.00070807e-01]
--------------
Epoch: 87
Predicted Result: [0 0 0 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 5.00070807e-01]
--------------
Epoch: 88
Predicted Result: [0 0 0 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 5.00070807e-01]
--------------
Epoch: 89
Predicted Result: [0 0 0 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 5.00070807e-01]
--------------
Epoch: 90
Predicted Result: [0 0 0 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 5.00070807e-01]
--------------
Epoch: 91
Predicted Result: [0 0 0 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 5.00070807e-01]
--------------
Epoch: 92
Predicted Result: [0 0 0 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 5.00070807e-01]
--------------
Epoch: 93
Predicted Result: [0 0 0 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 5.00070807e-01]
--------------
Epoch: 94
Predicted Result: [0 0 0 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 5.00070807e-01]
--------------
Epoch: 95
Predicted Result: [0 0 0 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 5.00070807e-01]
--------------
Epoch: 96
Predicted Result: [0 0 0 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 5.00070807e-01]
--------------
Epoch: 97
Predicted Result: [0 0 0 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 5.00070807e-01]
--------------
Epoch: 98
Predicted Result: [0 0 0 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 5.00070807e-01]
--------------
Epoch: 99
Predicted Result: [0 0 0 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 5.00070807e-01]
--------------
Epoch: 100
Predicted Result: [0 0 0 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 5.00070807e-01]
--------------
Epoch: 101
Predicted Result: [0 0 0 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 5.00070807e-01]
--------------
Epoch: 102
Predicted Result: [0 0 0 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 5.00070807e-01]
--------------
Epoch: 103
Predicted Result: [0 0 0 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 5.00070807e-01]
--------------
Epoch: 104
Predicted Result: [0 0 0 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 5.00070807e-01]
--------------
Epoch: 105
Predicted Result: [0 0 0 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 5.00070807e-01]
--------------
Epoch: 106
Predicted Result: [0 0 0 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 5.00070807e-01]
--------------
Epoch: 107
Predicted Result: [0 0 0 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 5.00070807e-01]
--------------
Epoch: 108
Predicted Result: [0 0 0 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 5.00070807e-01]
--------------
Epoch: 109
Predicted Result: [0 0 0 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 5.00070807e-01]
--------------
Epoch: 110
Predicted Result: [0 0 0 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 5.00070807e-01]
--------------
Epoch: 111
Predicted Result: [0 0 0 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 5.00070807e-01]
--------------
Epoch: 112
Predicted Result: [0 0 0 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 5.00070807e-01]
--------------
Epoch: 113
Predicted Result: [0 0 0 1]
Error:
0    0
1    0
2    0
3    0
Name: y, dtype: int64
Updated Weights: [8.66176146e-05 5.00060112e-01 5.00070807e-01]
--------------
Epoch: 114

In [102]:
w = np.array([2, 2])
x = np.array([2, 2])

***Dot Product***

In [103]:
dot = np.dot(w, x) 
print(f"Weighted Sum: {dot}")

Weighted Sum: 8

***Normal Distribution***

In [104]:
random = np.random.seed(42)

In [105]:
random_normal = np.random.randn(3)
print(f"Random Values: {random_normal}")

Random Values: [ 0.49671415 -0.1382643   0.64768854]

***Concatenation***

In [106]:
data = {
    'x1' : [0, 0, 1, 1],
    'x2' : [0, 1, 0, 1],
    'y' : [0, 0, 0, 1]
}

AND = pd.DataFrame(data) 
AND

   x1  x2  y
0   0   0  0
1   0   1  0
2   1   0  0
3   1   1  1

In [107]:
x = AND.drop('y', axis=1)
y = AND['y']
y.to_frame()
bias = np.c_[x, -np.ones((len(x), 1))]
bias

array([[ 0.,  0., -1.],
       [ 0.,  1., -1.],
       [ 1.,  0., -1.],
       [ 1.,  1., -1.]])