In [2]:
import pandas as pd

df = pd.read_csv('student_data.csv')
df.head(3)

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka

In [3]:
# adding a column with cinstant value
df['Country'] = 'Bangladesh'
df.sample(3)

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Country
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram,Bangladesh
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka,Bangladesh
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna,Bangladesh

In [4]:
# total marks
df['Total Marks'] = df['Data Structure Marks'] + df['Algorithm Marks'] + df['Python Marks']
df.sample(3)

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Country,Total Marks
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka,Bangladesh,NaN
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram,Bangladesh,257.0
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna,Bangladesh,NaN

In [5]:
# first name last name
df['First Name'] = df['FullName'].str.split(' ').str[0]
df['Last Name'] = df['FullName'].str.split(' ').str[1]
df.sample(3)

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Country,Total Marks,First Name,Last Name
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka,Bangladesh,256.0,Wahiduzzaman,NaN
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet,Bangladesh,266.0,Priya,Sharma
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram,Bangladesh,NaN,Kamal,Uddin

In [6]:
df.to_csv('new_student_data.csv')

***Unique Values***

In [7]:
# total unique values
print(f"Unique Names: {df['FullName'].unique()}")
print(f"\nTotal Unique Names: {df['FullName'].nunique()}")

# 'unique' works on a series meanwhile 'nunique' works on a data frame

Unique Names: ['Alif Rahman' 'Fatima Akhter' 'Imran Hossain' 'Jannatul Ferdous'
 'Kamal Uddin' 'Laila Begum' 'Mahmudul Hasan' 'Nadia Islam' 'Omar Faruq'
 'Priya Sharma' 'Rahim Sheikh' 'Sadia Chowdhury' 'Tanvir Ahmed'
 'Urmi Akter' 'Wahiduzzaman' 'Ziaur Rahman' 'Afsana Mimi' 'Babul Ahmed'
 'Faria Rahman' 'Nasir Khan']

Total Unique Names: 20

In [8]:
# 'unique' works on a series meanwhile 'nunique' works on a data frame
df.nunique()

StudentID               20
FullName                20
Data Structure Marks    12
Algorithm Marks         12
Python Marks            12
CompletionStatus         3
EnrollmentDate          20
Instructor               3
Location                 5
Country                  1
Total Marks             11
First Name              20
Last Name               16
dtype: int64

***Check Null***

isnull:
(null -> ture) and
(not null -> false)

In [9]:
df.isnull().sample(3)

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Country,Total Marks,First Name,Last Name
4,False,False,True,True,False,False,False,False,False,False,True,False,False
12,False,False,False,False,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False,False,False,False,False

In [10]:
df['Data Structure Marks'].isnull().sample(3)

14    False
19    False
3     False
Name: Data Structure Marks, dtype: bool

notnull:
(null -> false) and
(not null -> true)

In [11]:
df['Data Structure Marks'].notnull().sample(3)

8     True
19    True
12    True
Name: Data Structure Marks, dtype: bool

hasnans: if one null vaule exist -> true

In [12]:
# if one null vaule exist -> true 
df['Data Structure Marks'].hasnans

True

In [13]:
df['StudentID'].hasnans

False

***Handling Duplicate Values***

In [14]:
print(f"Total Duplicate Vlaues: {df.duplicated().sum()}")

Total Duplicate Vlaues: 0

In [15]:
# deleting duplicate values
df.drop_duplicates().sample(3)

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Country,Total Marks,First Name,Last Name
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi,Bangladesh,228.0,Laila,Begum
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka,Bangladesh,NaN,Mahmudul,Hasan
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka,Bangladesh,256.0,Wahiduzzaman,NaN

In [16]:
df.drop_duplicates(subset=['FullName']).sample(3)

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Country,Total Marks,First Name,Last Name
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka,Bangladesh,261.0,Nasir,Khan
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet,Bangladesh,261.0,Babul,Ahmed
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram,Bangladesh,NaN,Faria,Rahman

***Handling Null Values***

In [17]:
df.dropna()

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Country,Total Marks,First Name,Last Name
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka,Bangladesh,258.0,Alif,Rahman
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka,Bangladesh,261.0,Imran,Hossain
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet,Bangladesh,238.0,Jannatul,Ferdous
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi,Bangladesh,228.0,Laila,Begum
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram,Bangladesh,247.0,Nadia,Islam
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka,Bangladesh,220.0,Omar,Faruq
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet,Bangladesh,266.0,Priya,Sharma
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram,Bangladesh,257.0,Sadia,Chowdhury
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka,Bangladesh,229.0,Tanvir,Ahmed
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka,Bangladesh,273.0,Afsana,Mimi
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet,Bangladesh,261.0,Babul,Ahmed
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka,Bangladesh,261.0,Nasir,Khan

In [18]:
df.dropna(subset=['Algorithm Marks', 'Python Marks'])

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Country,Total Marks,First Name,Last Name
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka,Bangladesh,258.0,Alif,Rahman
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka,Bangladesh,261.0,Imran,Hossain
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet,Bangladesh,238.0,Jannatul,Ferdous
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi,Bangladesh,228.0,Laila,Begum
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram,Bangladesh,247.0,Nadia,Islam
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka,Bangladesh,220.0,Omar,Faruq
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet,Bangladesh,266.0,Priya,Sharma
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram,Bangladesh,257.0,Sadia,Chowdhury
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka,Bangladesh,229.0,Tanvir,Ahmed
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka,Bangladesh,256.0,Wahiduzzaman,NaN
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka,Bangladesh,273.0,Afsana,Mimi
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet,Bangladesh,261.0,Babul,Ahmed
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka,Bangladesh,261.0,Nasir,Khan

In [19]:
df['FullName'].fillna('Unknown')

0          Alif Rahman
1        Fatima Akhter
2        Imran Hossain
3     Jannatul Ferdous
4          Kamal Uddin
5          Laila Begum
6       Mahmudul Hasan
7          Nadia Islam
8           Omar Faruq
9         Priya Sharma
10        Rahim Sheikh
11     Sadia Chowdhury
12        Tanvir Ahmed
13          Urmi Akter
14        Wahiduzzaman
15        Ziaur Rahman
16         Afsana Mimi
17         Babul Ahmed
18        Faria Rahman
19          Nasir Khan
Name: FullName, dtype: object

In [20]:
df['Python Marks'].fillna(df['Python Marks'].mean())

0     88.000000
1     85.666667
2     85.000000
3     82.000000
4     95.000000
5     78.000000
6     85.666667
7     85.000000
8     76.000000
9     88.000000
10    91.000000
11    87.000000
12    79.000000
13    85.666667
14    84.000000
15    85.666667
16    93.000000
17    85.000000
18    85.666667
19    89.000000
Name: Python Marks, dtype: float64

***Statistical FUnctions***

In [21]:
print("Course: Data Structure\n")
print(f"Total Sumation: {df['Data Structure Marks'].sum()}")
print(f"Maximum Number: {df['Data Structure Marks'].max()}")
print(f"Minimum Number: {df['Data Structure Marks'].min()}")
print(f"Average Number: {df['Data Structure Marks'].mean()}")
print(f"Median Number: {df['Data Structure Marks'].median()}")
print(f"Mode Number:\n{df['Data Structure Marks'].mode()}")
print(f"Standard Deviation: {df['Data Structure Marks'].std()}")
print(f"Correlation: {df['Data Structure Marks'].min()}")

Course: Data Structure

Total Sumation: 1344.0
Maximum Number: 94.0
Minimum Number: 72.0
Average Number: 84.0
Median Number: 85.5
Mode Number:
0    75.0
1    85.0
2    86.0
3    88.0
Name: Data Structure Marks, dtype: float64
Standard Deviation: 6.501281924871945
Correlation: 72.0

In [22]:
# Correlation Matrix
df[['Data Structure Marks', 'Algorithm Marks', 'Python Marks']].corr()

                      Data Structure Marks  Algorithm Marks  Python Marks
Data Structure Marks              1.000000         1.000000      0.893455
Algorithm Marks                   1.000000         1.000000      0.893455
Python Marks                      0.893455         0.893455      1.000000

In [23]:
df['Total Marks'] = df.iloc[ :: , 2:5].sum(axis=1)
df.sample(3)

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Country,Total Marks,First Name,Last Name
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet,Bangladesh,261.0,Babul,Ahmed
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram,Bangladesh,257.0,Sadia,Chowdhury
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka,Bangladesh,261.0,Nasir,Khan

In [24]:
df.describe()

       Data Structure Marks  Algorithm Marks  Python Marks  Total Marks
count             16.000000        16.000000     15.000000    20.000000
mean              84.000000        84.000000     85.666667   198.650000
std                6.501282         6.501282      5.394000    86.189678
min               72.000000        72.000000     76.000000     0.000000
25%               79.500000        79.500000     83.000000   178.000000
50%               85.500000        85.500000     85.000000   233.500000
75%               88.250000        88.250000     88.500000   258.750000
max               94.000000        94.000000     95.000000   273.000000

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   StudentID             20 non-null     object
 1   FullName              20 non-null     object
 2   Data Structure Marks  16 non-null     float64
 3   Algorithm Marks       16 non-null     float64
 4   Python Marks          15 non-null     float64
 5   CompletionStatus      20 non-null     object
 6   EnrollmentDate        20 non-null     object
 7   Instructor            20 non-null     object
 8   Location              20 non-null     object
 9   Country               20 non-null     object
 10  Total Marks           20 non-null     float64
 11  First Name            20 non-null     object
 12  Last Name             19 non-null     object
dtypes: float64(4), object(9)
memory usage: 2.2+ KB

***Apply Function***

In [26]:
# min max scaling

mn = df['Total Marks'].min()
mx = df['Total Marks'].max()

df['Scaled Marks'] = df['Total Marks'].apply(lambda x : (x - mn) / (mx - mn))

df.sample(3)

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Country,Total Marks,First Name,Last Name,Scaled Marks
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka,Bangladesh,261.0,Nasir,Khan,0.956044
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram,Bangladesh,184.0,Fatima,Akhter,0.673993
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram,Bangladesh,95.0,Kamal,Uddin,0.347985

In [27]:
# custom build function

def grading_system(marks):
    if marks >= 260:
        return 'A+'
    elif marks >= 210:
        return 'A'
    else:
        return 'A-'

df['Grade'] = df['Total Marks'].apply(grading_system)

df.sample(3)

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Country,Total Marks,First Name,Last Name,Scaled Marks,Grade
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka,Bangladesh,261.0,Imran,Hossain,0.956044,A+
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet,Bangladesh,261.0,Babul,Ahmed,0.956044,A+
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram,Bangladesh,247.0,Nadia,Islam,0.904762,A

***Date-Time***

In [28]:
d_f = pd.read_csv('student_completed_data.csv')

d_f.sample(3)

,StudentID,FullName,CompletionStatus,EnrollmentDate,FinishedDate,Instructor,Location,Total Marks
18,PH0019,Faria Rahman,Completed,2024-04-19,2024-08-17,Mr. Karim,Sylhet,277
17,PH0018,Babul Ahmed,Completed,2024-06-23,2024-09-20,Mr. David,Dhaka,278
6,PH0007,Mahmudul Hasan,Completed,2024-06-07,2024-07-20,Mr. David,Chattogram,249

In [29]:
# data type: object -> datetime
d_f['EnrollmentDate'] = pd.to_datetime(d_f['EnrollmentDate'])
d_f['FinishedDate'] = pd.to_datetime(d_f['FinishedDate'])

In [30]:
d_f['Enrollment Day'] = d_f['EnrollmentDate'].dt.day_name()
d_f['Enrollment Month'] = d_f['EnrollmentDate'].dt.month_name()
d_f['Enrollment Year'] = d_f['EnrollmentDate'].dt.year
d_f['Total Time'] = d_f['FinishedDate'] - d_f['EnrollmentDate']
d_f.sample(3)

,StudentID,FullName,CompletionStatus,EnrollmentDate,FinishedDate,Instructor,Location,Total Marks,Enrollment Day,Enrollment Month,Enrollment Year,Total Time
8,PH0009,Omar Faruq,Completed,2024-02-12,2024-06-08,Mr. Karim,Dhaka,291,Monday,February,2024,117 days
0,PH0001,Alif Rahman,Completed,2024-09-01,2024-12-23,Ms. Salma,Khulna,300,Sunday,September,2024,113 days
9,PH0010,Priya Sharma,Completed,2024-06-19,2024-08-19,Mr. David,Dhaka,286,Wednesday,June,2024,61 days

***Groupby***

In [31]:
d_f = pd.read_csv('student_completed_data.csv')

d_f.sample(3)

,StudentID,FullName,CompletionStatus,EnrollmentDate,FinishedDate,Instructor,Location,Total Marks
19,PH0020,Tariq Hasan,Completed,2024-07-21,2024-10-11,Mr. Karim,Khulna,253
9,PH0010,Priya Sharma,Completed,2024-06-19,2024-08-19,Mr. David,Dhaka,286
7,PH0008,Nadia Islam,Completed,2024-03-22,2024-05-01,Ms. Salma,Khulna,246

In [32]:
instructor_group = d_f.groupby('Instructor')
instructor_group

In [33]:
for instructor, df_ins in instructor_group:
    print(f"\nInstructor: {instructor}")
    display(df_ins)

Instructor: Mr. David

,StudentID,FullName,CompletionStatus,EnrollmentDate,FinishedDate,Instructor,Location,Total Marks
4,PH0005,Kamal Uddin,Completed,2024-02-01,2024-04-17,Mr. David,Sylhet,254
5,PH0006,Laila Begum,Completed,2024-09-07,2024-12-31,Mr. David,Khulna,272
6,PH0007,Mahmudul Hasan,Completed,2024-06-07,2024-07-20,Mr. David,Chattogram,249
9,PH0010,Priya Sharma,Completed,2024-06-19,2024-08-19,Mr. David,Dhaka,286
12,PH0013,Tanvir Ahmed,Completed,2024-06-07,2024-08-03,Mr. David,Dhaka,248
13,PH0014,Urmi Akter,Completed,2024-01-04,2024-03-23,Mr. David,Sylhet,285
14,PH0015,Wahiduzzaman,Completed,2024-02-22,2024-05-16,Mr. David,Rajshahi,291
16,PH0017,Afsana Mimi,Completed,2024-01-18,2024-03-16,Mr. David,Khulna,236
17,PH0018,Babul Ahmed,Completed,2024-06-23,2024-09-20,Mr. David,Dhaka,278

Instructor: Mr. Karim

,StudentID,FullName,CompletionStatus,EnrollmentDate,FinishedDate,Instructor,Location,Total Marks
1,PH0002,Fatima Akhter,Completed,2024-08-11,2024-11-07,Mr. Karim,Dhaka,271
3,PH0004,Jannatul Ferdous,Completed,2024-07-05,2024-09-23,Mr. Karim,Khulna,270
8,PH0009,Omar Faruq,Completed,2024-02-12,2024-06-08,Mr. Karim,Dhaka,291
10,PH0011,Rahim Sheikh,Completed,2024-03-14,2024-06-11,Mr. Karim,Sylhet,283
11,PH0012,Sadia Chowdhury,Completed,2024-08-04,2024-10-25,Mr. Karim,Sylhet,266
18,PH0019,Faria Rahman,Completed,2024-04-19,2024-08-17,Mr. Karim,Sylhet,277
19,PH0020,Tariq Hasan,Completed,2024-07-21,2024-10-11,Mr. Karim,Khulna,253

Instructor: Ms. Salma

,StudentID,FullName,CompletionStatus,EnrollmentDate,FinishedDate,Instructor,Location,Total Marks
0,PH0001,Alif Rahman,Completed,2024-09-01,2024-12-23,Ms. Salma,Khulna,300
2,PH0003,Imran Hossain,Completed,2024-05-08,2024-08-08,Ms. Salma,Dhaka,269
7,PH0008,Nadia Islam,Completed,2024-03-22,2024-05-01,Ms. Salma,Khulna,246
15,PH0016,Ziaur Rahman,Completed,2024-03-23,2024-06-21,Ms. Salma,Rajshahi,234

In [34]:
instructor_group.describe()

           Total Marks                                                      \
                 count        mean        std    min    25%    50%     75%
Instructor
Mr. David          9.0  266.555556  20.063095  236.0  249.0  272.0  285.00
Mr. Karim          7.0  273.000000  12.261049  253.0  268.0  271.0  280.00
Ms. Salma          4.0  262.250000  29.055980  234.0  243.0  257.5  276.75


              max
Instructor
Mr. David   291.0
Mr. Karim   291.0
Ms. Salma   300.0

In [37]:
mean_marks = instructor_group['Total Marks'].mean()
mean_marks

Instructor
Mr. David    266.555556
Mr. Karim    273.000000
Ms. Salma    262.250000
Name: Total Marks, dtype: float64

In [41]:
# replacing null value with respect to groupby (instructor) mean
d_f['Total Marks'] = d_f['Total Marks'].fillna(d_f['Instructor'].map(mean_marks))
d_f.sample(3)

,StudentID,FullName,CompletionStatus,EnrollmentDate,FinishedDate,Instructor,Location,Total Marks
8,PH0009,Omar Faruq,Completed,2024-02-12,2024-06-08,Mr. Karim,Dhaka,291
0,PH0001,Alif Rahman,Completed,2024-09-01,2024-12-23,Ms. Salma,Khulna,300
12,PH0013,Tanvir Ahmed,Completed,2024-06-07,2024-08-03,Mr. David,Dhaka,248